CREATE TABLE sessions (id TEXT PRIMARY KEY, created_at BIGINT NOT NULL, cwd TEXT NOT NULL, parent_session_id TEXT, metadata JSONB, project_id TEXT NOT NULL DEFAULT '');
CREATE INDEX idx_sessions_created_at ON sessions(created_at DESC);
CREATE INDEX idx_sessions_cwd_created_at ON sessions(cwd, created_at DESC);
CREATE TABLE session_sequences (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, next_seq BIGINT NOT NULL);
CREATE TABLE session_stats (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, message_count BIGINT NOT NULL, cached_tokens DOUBLE PRECISION NOT NULL, uncached_tokens DOUBLE PRECISION NOT NULL, total_tokens DOUBLE PRECISION NOT NULL, cost_total DOUBLE PRECISION NOT NULL);
CREATE TABLE entries (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, seq BIGINT NOT NULL, id TEXT NOT NULL, parent_id TEXT, type TEXT NOT NULL, timestamp BIGINT NOT NULL, payload JSONB NOT NULL, PRIMARY KEY(session_id,id), UNIQUE(session_id,seq));
CREATE INDEX idx_entries_session_parent ON entries(session_id,parent_id);
CREATE INDEX idx_entries_session_type_seq ON entries(session_id,type,seq);
CREATE TABLE lanes (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, lane TEXT NOT NULL, leaf_id TEXT, open_operation_id TEXT, PRIMARY KEY(session_id,lane));
CREATE TABLE records (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, seq BIGINT NOT NULL, id TEXT NOT NULL, lane TEXT NOT NULL, run_id TEXT, type TEXT NOT NULL, op_kind TEXT, timestamp BIGINT NOT NULL, payload JSONB NOT NULL, PRIMARY KEY(session_id,id), UNIQUE(session_id,seq));
CREATE INDEX idx_records_session_lane_seq ON records(session_id,lane,seq);
CREATE INDEX idx_records_session_type_seq ON records(session_id,type,seq);
CREATE INDEX idx_records_session_type_op_kind_seq ON records(session_id,type,op_kind,seq);
CREATE INDEX idx_records_session_lane_type_seq ON records(session_id,lane,type,seq);
CREATE INDEX idx_records_session_lane_type_op_kind_seq ON records(session_id,lane,type,op_kind,seq);
CREATE INDEX idx_records_session_run_id_seq ON records(session_id,run_id,seq);
CREATE TABLE lane_moves (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, seq BIGINT NOT NULL, lane TEXT NOT NULL, leaf_id TEXT, PRIMARY KEY(session_id,seq));
CREATE TABLE facts (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, seq BIGINT NOT NULL, kind TEXT NOT NULL, key TEXT, value JSONB, PRIMARY KEY(session_id,seq));
CREATE INDEX idx_facts_session_kind_key_seq ON facts(session_id,kind,key,seq);
CREATE TABLE branch_entries (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, branch_id TEXT NOT NULL, entry_id TEXT NOT NULL, entry_seq BIGINT NOT NULL, entry_type TEXT, custom_type TEXT, PRIMARY KEY(session_id,branch_id,entry_id));
CREATE INDEX idx_branch_entries_session_branch_seq ON branch_entries(session_id,branch_id,entry_seq);
CREATE INDEX idx_branch_entries_session_entry ON branch_entries(session_id,entry_id,branch_id,entry_seq);
CREATE INDEX idx_branch_entries_session_branch_type_seq ON branch_entries(session_id,branch_id,entry_type,entry_seq);
CREATE INDEX idx_branch_entries_session_branch_custom_seq ON branch_entries(session_id,branch_id,custom_type,entry_seq);
CREATE TABLE branch_tips (session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, branch_id TEXT NOT NULL, tip_id TEXT NOT NULL, PRIMARY KEY(session_id,tip_id), UNIQUE(session_id,branch_id));
CREATE TABLE writer_leases (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, owner_id TEXT NOT NULL, fence BIGINT NOT NULL, expires_at_ms BIGINT NOT NULL);
